package net.divinerpg.helper.mobs;

import net.divinerpg.helper.DivineAPI;
import net.divinerpg.vethea.entity.EntityAcidHag;
import net.divinerpg.vethea.entity.EntityBiphron;
import net.divinerpg.vethea.entity.EntityBohemite;
import net.divinerpg.vethea.entity.EntityCryptKeeper;
import net.divinerpg.vethea.entity.EntityCymesoid;
import net.divinerpg.vethea.entity.EntityDissiment;
import net.divinerpg.vethea.entity.EntityDreamwrecker;
import net.divinerpg.vethea.entity.EntityDuo;
import net.divinerpg.vethea.entity.EntityEhu;
import net.divinerpg.vethea.entity.EntityEndiku;
import net.divinerpg.vethea.entity.EntityEnt;
import net.divinerpg.vethea.entity.EntityGalroid;
import net.divinerpg.vethea.entity.EntityGorgosion;
import net.divinerpg.vethea.entity.EntityHelio;
import net.divinerpg.vethea.entity.EntityHiveQueen;
import net.divinerpg.vethea.entity.EntityHiveSoldier;
import net.divinerpg.vethea.entity.EntityHoverStinger;
import net.divinerpg.vethea.entity.EntityHungerHungry;
import net.divinerpg.vethea.entity.EntityHusk;
import net.divinerpg.vethea.entity.EntityKaros;
import net.divinerpg.vethea.entity.EntityKazrotic;
import net.divinerpg.vethea.entity.EntityLadyLuna;
import net.divinerpg.vethea.entity.EntityLheiva;
import net.divinerpg.vethea.entity.EntityLorga;
import net.divinerpg.vethea.entity.EntityLorgaFlight;
import net.divinerpg.vethea.entity.EntityMandragora;
import net.divinerpg.vethea.entity.EntityMysteriousManLayer1;
import net.divinerpg.vethea.entity.EntityMysteriousManLayer2;
import net.divinerpg.vethea.entity.EntityMysteriousManLayer3;
import net.divinerpg.vethea.entity.EntityQuadro;
import net.divinerpg.vethea.entity.EntityRaglok;
import net.divinerpg.vethea.entity.EntityShadahier;
import net.divinerpg.vethea.entity.EntityStoneGolem;
import net.divinerpg.vethea.entity.EntityTempleGuardian;
import net.divinerpg.vethea.entity.EntityTocaxin;
import net.divinerpg.vethea.entity.EntityTwins;
import net.divinerpg.vethea.entity.EntityVermenous;
import net.divinerpg.vethea.entity.EntityVhraak;
import net.divinerpg.vethea.entity.EntityWreck;
import net.divinerpg.vethea.entity.EntityZone;
import net.divinerpg.vethea.entity.EntityZoragon;
import net.divinerpg.vethea.entity.projectile.EntityAmthirmisDisk;
import net.divinerpg.vethea.entity.projectile.EntityArksianeDisk;
import net.divinerpg.vethea.entity.projectile.EntityBouncingProjectile;
import net.divinerpg.vethea.entity.projectile.EntityCermileDisk;
import net.divinerpg.vethea.entity.projectile.EntityDarvenDisk;
import net.divinerpg.vethea.entity.projectile.EntityEvernightProjectile;
import net.divinerpg.vethea.entity.projectile.EntityEversightProjectile;
import net.divinerpg.vethea.entity.projectile.EntityHeliosisDisk;
import net.divinerpg.vethea.entity.projectile.EntityKarosDisk;
import net.divinerpg.vethea.entity.projectile.EntityPardimalDisk;
import net.divinerpg.vethea.entity.projectile.EntityQuadroticDisk;
import net.divinerpg.vethea.entity.projectile.EntityTeakerDisk;
import net.divinerpg.vethea.entity.projectile.EntityVetheanCannonEversight;
import net.divinerpg.vethea.entity.projectile.EntityVetheanCannonShot;

public class VetheaMobRegistry {

	public static void init(){
		DivineAPI.registerProjectile(EntityAmthirmisDisk.class, "Amthirmis Disk");
		DivineAPI.registerProjectile(EntityArksianeDisk.class, "Arksiane Disk");
		DivineAPI.registerProjectile(EntityCermileDisk.class, "Cermile Disk");
		DivineAPI.registerProjectile(EntityDarvenDisk.class, "Darven Disk");
		DivineAPI.registerProjectile(EntityHeliosisDisk.class, "Heliosis Disk");
		DivineAPI.registerProjectile(EntityKarosDisk.class, "Karos Disk");
		DivineAPI.registerProjectile(EntityPardimalDisk.class, "Pardimal Disk");
		DivineAPI.registerProjectile(EntityQuadroticDisk.class, "Quadrotic Disk");
		DivineAPI.registerProjectile(EntityTeakerDisk.class, "Teaker Disk");
		
		DivineAPI.registerProjectile(EntityBouncingProjectile.class, "Staff");
		DivineAPI.registerProjectile(EntityEvernightProjectile.class, "Evernight");
		DivineAPI.registerProjectile(EntityVetheanCannonShot.class, "Cannon");
		DivineAPI.registerProjectile(EntityVetheanCannonEversight.class, "Cannon Eversight");
		DivineAPI.registerProjectile(EntityEversightProjectile.class, "Eversight");
		
		DivineAPI.registerDivineRPGMob(EntityVermenous.class, "Vermenous");
        DivineAPI.registerDivineRPGMob(EntityEnt.class, "Ent");
        DivineAPI.registerDivineRPGMob(EntityCymesoid.class, "Cymesoid");
        DivineAPI.registerDivineRPGMob(EntityDreamwrecker.class, "Dream Wrecker");
        DivineAPI.registerDivineRPGMob(EntityTocaxin.class, "Tocaxin");
        DivineAPI.registerDivineRPGMob(EntityShadahier.class, "Shadahier");
        DivineAPI.registerDivineRPGMob(EntityAcidHag.class, "Acid Hag");
        DivineAPI.registerDivineRPGMob(EntityKazrotic.class, "Kazrotic");
        DivineAPI.registerDivineRPGMob(EntityHelio.class, "Helio");
        DivineAPI.registerDivineRPGMob(EntityGorgosion.class, "Gorgosion");
        DivineAPI.registerDivineRPGMob(EntityHoverStinger.class, "Hoverstinger");
        DivineAPI.registerDivineRPGMob(EntityZone.class, "Zone");
        DivineAPI.registerDivineRPGMob(EntityZoragon.class, "Zoragon");
        DivineAPI.registerDivineRPGMob(EntityDissiment.class, "Dissiment");
        DivineAPI.registerDivineRPGMob(EntityVhraak.class, "Vhraak");
        DivineAPI.registerDivineRPGMob(EntityGalroid.class, "Galroid");
        DivineAPI.registerDivineRPGMob(EntityLadyLuna.class, "Lady Luna");
        DivineAPI.registerDivineRPGMob(EntityBohemite.class, "Bohemite");
        DivineAPI.registerDivineRPGMob(EntityWreck.class, "Wreck");
        DivineAPI.registerDivineRPGMob(EntityBiphron.class, "Biphron");
        DivineAPI.registerDivineRPGMob(EntityHiveQueen.class, "Hive Queen");
        DivineAPI.registerDivineRPGMob(EntityHiveSoldier.class, "hivesoldier");
        DivineAPI.registerDivineRPGMob(EntityLheiva.class, "lheiva");
        DivineAPI.registerDivineRPGMob(EntityMandragora.class, "mandragora");
        DivineAPI.registerDivineRPGMob(EntityTwins.class, "Twins");
        DivineAPI.registerDivineRPGMob(EntityKaros.class, "Karos");
        DivineAPI.registerDivineRPGMob(EntityRaglok.class, "Raglok");
        DivineAPI.registerDivineRPGMob(EntityQuadro.class, "Quadro");
        DivineAPI.registerDivineRPGMob(EntityDuo.class, "Duo");
        DivineAPI.registerDivineRPGMob(EntityEndiku.class, "Endiku");
        DivineAPI.registerDivineRPGMob(EntityLorga.class, "Lorga");
        DivineAPI.registerDivineRPGMob(EntityLorgaFlight.class, "Lorga Flight");
        DivineAPI.registerDivineRPGMob(EntityMysteriousManLayer1.class, "Mysterious Man 1");
        DivineAPI.registerDivineRPGMob(EntityMysteriousManLayer2.class, "Mysterious Man 2");
        DivineAPI.registerDivineRPGMob(EntityMysteriousManLayer3.class, "Mysterious Man 3");
        DivineAPI.registerDivineRPGMob(EntityHungerHungry.class, "Hunger Hungry");
        DivineAPI.registerDivineRPGMob(EntityCryptKeeper.class, "Crypt Keeper");
        DivineAPI.registerDivineRPGMob(EntityTempleGuardian.class, "Temple Guardian");
        DivineAPI.registerDivineRPGMob(EntityEhu.class, "Ehu");
        DivineAPI.registerDivineRPGMob(EntityStoneGolem.class, "Stone Golem");
        DivineAPI.registerDivineRPGMob(EntityHusk.class, "Husk");
	}
}