package net.divinerpg.client.render.entity;

import net.divinerpg.client.render.EntityResourceLocation;
import net.divinerpg.client.render.RenderDivineMob;
import net.divinerpg.client.render.RenderIconProjectile;
import net.divinerpg.client.render.RenderProjectile;
import net.divinerpg.helper.items.VetheanItems;
import net.divinerpg.vethea.entity.EntityAcidHag;
import net.divinerpg.vethea.entity.EntityBiphron;
import net.divinerpg.vethea.entity.EntityBohemite;
import net.divinerpg.vethea.entity.EntityCryptKeeper;
import net.divinerpg.vethea.entity.EntityCymesoid;
import net.divinerpg.vethea.entity.EntityDissiment;
import net.divinerpg.vethea.entity.EntityDreamwrecker;
import net.divinerpg.vethea.entity.EntityDuo;
import net.divinerpg.vethea.entity.EntityEhu;
import net.divinerpg.vethea.entity.EntityEndiku;
import net.divinerpg.vethea.entity.EntityEnt;
import net.divinerpg.vethea.entity.EntityGalroid;
import net.divinerpg.vethea.entity.EntityGorgosion;
import net.divinerpg.vethea.entity.EntityHelio;
import net.divinerpg.vethea.entity.EntityHerbomancer;
import net.divinerpg.vethea.entity.EntityHiveQueen;
import net.divinerpg.vethea.entity.EntityHiveSoldier;
import net.divinerpg.vethea.entity.EntityHoverStinger;
import net.divinerpg.vethea.entity.EntityHungerHungry;
import net.divinerpg.vethea.entity.EntityHusk;
import net.divinerpg.vethea.entity.EntityKaros;
import net.divinerpg.vethea.entity.EntityKazrotic;
import net.divinerpg.vethea.entity.EntityLadyLuna;
import net.divinerpg.vethea.entity.EntityLheiva;
import net.divinerpg.vethea.entity.EntityLorga;
import net.divinerpg.vethea.entity.EntityLorgaFlight;
import net.divinerpg.vethea.entity.EntityMandragora;
import net.divinerpg.vethea.entity.EntityMysteriousManLayer1;
import net.divinerpg.vethea.entity.EntityMysteriousManLayer2;
import net.divinerpg.vethea.entity.EntityMysteriousManLayer3;
import net.divinerpg.vethea.entity.EntityQuadro;
import net.divinerpg.vethea.entity.EntityRaglok;
import net.divinerpg.vethea.entity.EntityShadahier;
import net.divinerpg.vethea.entity.EntityStoneGolem;
import net.divinerpg.vethea.entity.EntityTempleGuardian;
import net.divinerpg.vethea.entity.EntityTocaxin;
import net.divinerpg.vethea.entity.EntityTwins;
import net.divinerpg.vethea.entity.EntityVermenous;
import net.divinerpg.vethea.entity.EntityVhraak;
import net.divinerpg.vethea.entity.EntityWreck;
import net.divinerpg.vethea.entity.EntityZone;
import net.divinerpg.vethea.entity.EntityZoragon;
import net.divinerpg.vethea.entity.projectile.EntityAmthirmisDisk;
import net.divinerpg.vethea.entity.projectile.EntityArksianeDisk;
import net.divinerpg.vethea.entity.projectile.EntityBouncingProjectile;
import net.divinerpg.vethea.entity.projectile.EntityCermileDisk;
import net.divinerpg.vethea.entity.projectile.EntityDarvenDisk;
import net.divinerpg.vethea.entity.projectile.EntityEvernightProjectile;
import net.divinerpg.vethea.entity.projectile.EntityEversightProjectile;
import net.divinerpg.vethea.entity.projectile.EntityHeliosisDisk;
import net.divinerpg.vethea.entity.projectile.EntityKarosDisk;
import net.divinerpg.vethea.entity.projectile.EntityPardimalDisk;
import net.divinerpg.vethea.entity.projectile.EntityQuadroticDisk;
import net.divinerpg.vethea.entity.projectile.EntityTeakerDisk;
import net.divinerpg.vethea.entity.projectile.EntityVetheanCannonEversight;
import net.divinerpg.vethea.entity.projectile.EntityVetheanCannonShot;
import net.divinerpg.vethea.entity.render.RenderBiphron;
import net.divinerpg.vethea.entity.render.RenderGalroid;
import net.divinerpg.vethea.entity.render.RenderHiveQueen;
import net.divinerpg.vethea.entity.render.RenderWreck;
import net.divinerpg.vethea.entity.render.model.AcidHag;
import net.divinerpg.vethea.entity.render.model.Biphron;
import net.divinerpg.vethea.entity.render.model.Boheimite;
import net.divinerpg.vethea.entity.render.model.CryptKeeper;
import net.divinerpg.vethea.entity.render.model.Cymesoid;
import net.divinerpg.vethea.entity.render.model.Dissiment;
import net.divinerpg.vethea.entity.render.model.Dreamwrecker;
import net.divinerpg.vethea.entity.render.model.Duo;
import net.divinerpg.vethea.entity.render.model.Ehu;
import net.divinerpg.vethea.entity.render.model.Endiku;
import net.divinerpg.vethea.entity.render.model.Ent;
import net.divinerpg.vethea.entity.render.model.Galroid;
import net.divinerpg.vethea.entity.render.model.Gorgosion;
import net.divinerpg.vethea.entity.render.model.Helio;
import net.divinerpg.vethea.entity.render.model.Herbomancer;
import net.divinerpg.vethea.entity.render.model.HiveQueen;
import net.divinerpg.vethea.entity.render.model.HiveSoldier;
import net.divinerpg.vethea.entity.render.model.HoverStinger;
import net.divinerpg.vethea.entity.render.model.Husk;
import net.divinerpg.vethea.entity.render.model.Karos;
import net.divinerpg.vethea.entity.render.model.Kazrotic;
import net.divinerpg.vethea.entity.render.model.LadyLuna;
import net.divinerpg.vethea.entity.render.model.Lheiva;
import net.divinerpg.vethea.entity.render.model.Lorga;
import net.divinerpg.vethea.entity.render.model.Lorgaflight;
import net.divinerpg.vethea.entity.render.model.Mandragora;
import net.divinerpg.vethea.entity.render.model.ModelHungerHungry;
import net.divinerpg.vethea.entity.render.model.MysteriousMan;
import net.divinerpg.vethea.entity.render.model.Quadro;
import net.divinerpg.vethea.entity.render.model.RaglokGogdure;
import net.divinerpg.vethea.entity.render.model.Shadahier;
import net.divinerpg.vethea.entity.render.model.StoneGolem;
import net.divinerpg.vethea.entity.render.model.Tocaxin;
import net.divinerpg.vethea.entity.render.model.Twins;
import net.divinerpg.vethea.entity.render.model.Vermenous;
import net.divinerpg.vethea.entity.render.model.Vhraak;
import net.divinerpg.vethea.entity.render.model.WreckForm1;
import net.divinerpg.vethea.entity.render.model.Zone;
import net.divinerpg.vethea.entity.render.model.Zoragon;
import net.minecraft.client.model.ModelBiped;
import cpw.mods.fml.client.registry.RenderingRegistry;

public class VetheaEntityRenderer {

	private static EntityResourceLocation x;
	
	public static void init(){
		RenderingRegistry.registerEntityRenderingHandler(EntityAmthirmisDisk.class, new RenderIconProjectile(VetheanItems.amthrimisDisk));
		RenderingRegistry.registerEntityRenderingHandler(EntityArksianeDisk.class, new RenderIconProjectile(VetheanItems.arksianeDisk));
		RenderingRegistry.registerEntityRenderingHandler(EntityCermileDisk.class, new RenderIconProjectile(VetheanItems.cermileDisk));
		RenderingRegistry.registerEntityRenderingHandler(EntityDarvenDisk.class, new RenderIconProjectile(VetheanItems.darvenDisk));
		RenderingRegistry.registerEntityRenderingHandler(EntityHeliosisDisk.class, new RenderIconProjectile(VetheanItems.heliosisDisk));
		RenderingRegistry.registerEntityRenderingHandler(EntityKarosDisk.class, new RenderIconProjectile(VetheanItems.karosDisk));
		RenderingRegistry.registerEntityRenderingHandler(EntityPardimalDisk.class, new RenderIconProjectile(VetheanItems.pardimalDisk));
		RenderingRegistry.registerEntityRenderingHandler(EntityQuadroticDisk.class, new RenderIconProjectile(VetheanItems.quadroticDisk));
		RenderingRegistry.registerEntityRenderingHandler(EntityTeakerDisk.class, new RenderIconProjectile(VetheanItems.teakerDisk));

		RenderingRegistry.registerEntityRenderingHandler(EntityBouncingProjectile.class, new RenderProjectile(EntityResourceLocation.staffProjectile));
		RenderingRegistry.registerEntityRenderingHandler(EntityEvernightProjectile.class, new RenderProjectile(EntityResourceLocation.evernight));
		RenderingRegistry.registerEntityRenderingHandler(EntityVetheanCannonShot.class, new RenderProjectile(EntityResourceLocation.cannon));
		RenderingRegistry.registerEntityRenderingHandler(EntityVetheanCannonEversight.class, new RenderProjectile(EntityResourceLocation.eversightCannon));
		RenderingRegistry.registerEntityRenderingHandler(EntityEversightProjectile.class, new RenderProjectile(EntityResourceLocation.eversight));

		RenderingRegistry.registerEntityRenderingHandler(EntityVermenous.class, new RenderDivineMob(new Vermenous(), 0.0F, x.VERMENOUS));
		RenderingRegistry.registerEntityRenderingHandler(EntityEnt.class, new RenderDivineMob(new Ent(), 0.0F, x.ENT));
		RenderingRegistry.registerEntityRenderingHandler(EntityCymesoid.class, new RenderDivineMob(new Cymesoid(), 0.0F, x.CYMESOID));
		RenderingRegistry.registerEntityRenderingHandler(EntityDreamwrecker.class, new RenderDivineMob(new Dreamwrecker(), 0.0F, x.DREAMWRECKER));
		RenderingRegistry.registerEntityRenderingHandler(EntityTocaxin.class, new RenderDivineMob(new Tocaxin(), 0.0F, x.TOCAXIN));
		RenderingRegistry.registerEntityRenderingHandler(EntityShadahier.class, new RenderDivineMob(new Shadahier(), 0.0F, x.SHADAHIER));
		RenderingRegistry.registerEntityRenderingHandler(EntityAcidHag.class, new RenderDivineMob(new AcidHag(), 0.0F, x.ACID_HAG));
		RenderingRegistry.registerEntityRenderingHandler(EntityKazrotic.class, new RenderDivineMob(new Kazrotic(), 0.0F, x.KAZROTIC));
		RenderingRegistry.registerEntityRenderingHandler(EntityHelio.class, new RenderDivineMob(new Helio(), 0.0F, x.HELIO));
		RenderingRegistry.registerEntityRenderingHandler(EntityGorgosion.class, new RenderDivineMob(new Gorgosion(), 0.0F, x.GORGOSION));
		RenderingRegistry.registerEntityRenderingHandler(EntityHoverStinger.class, new RenderDivineMob(new HoverStinger(), 0.0F, x.HOVER_STINGER));
		RenderingRegistry.registerEntityRenderingHandler(EntityZone.class, new RenderDivineMob(new Zone(), 0.0F, x.ZONE));
		RenderingRegistry.registerEntityRenderingHandler(EntityZoragon.class, new RenderDivineMob(new Zoragon(), 0.0F, x.ZORAGON));
		RenderingRegistry.registerEntityRenderingHandler(EntityDissiment.class, new RenderDivineMob(new Dissiment(), 0.0F, x.DISSIMENT));
		RenderingRegistry.registerEntityRenderingHandler(EntityVhraak.class, new RenderDivineMob(new Vhraak(), 0.0F, x.VHRAAK));
		RenderingRegistry.registerEntityRenderingHandler(EntityGalroid.class, new RenderGalroid(new Galroid(), 0.0F, x.GALROID));
		RenderingRegistry.registerEntityRenderingHandler(EntityLadyLuna.class, new RenderDivineMob(new LadyLuna(), 0.0F, x.LADY_LUNA_MELEE));
		RenderingRegistry.registerEntityRenderingHandler(EntityBohemite.class, new RenderDivineMob(new Boheimite(), 0.0F, x.BOHEMITE));
		RenderingRegistry.registerEntityRenderingHandler(EntityWreck.class, new RenderWreck(new WreckForm1(), 0.0F, x.WRECK));
		RenderingRegistry.registerEntityRenderingHandler(EntityBiphron.class, new RenderBiphron(new Biphron(), 0.0F, x.BIPHRON));
		RenderingRegistry.registerEntityRenderingHandler(EntityHiveQueen.class, new RenderHiveQueen(new HiveQueen(), 0.0F, x.HIVE_QUEEN));
		RenderingRegistry.registerEntityRenderingHandler(EntityHiveSoldier.class, new RenderDivineMob(new HiveSoldier(), 0.0F, x.HIVE_SOLDIER));
		RenderingRegistry.registerEntityRenderingHandler(EntityLheiva.class, new RenderDivineMob(new Lheiva(), 0.0F, x.LHEIVA));
		RenderingRegistry.registerEntityRenderingHandler(EntityTwins.class, new RenderDivineMob(new Twins(), 0.0F, x.TWINS));
		RenderingRegistry.registerEntityRenderingHandler(EntityQuadro.class, new RenderDivineMob(new Quadro(), 0.0F, x.QUADRO));
		RenderingRegistry.registerEntityRenderingHandler(EntityEndiku.class, new RenderDivineMob(new Endiku(), 0.0F, x.ENDIKU));
		RenderingRegistry.registerEntityRenderingHandler(EntityTempleGuardian.class, new RenderDivineMob(new ModelBiped(), 0.0F, x.TEMPLE_GUARDIAN));
		RenderingRegistry.registerEntityRenderingHandler(EntityMysteriousManLayer1.class, new RenderDivineMob(new MysteriousMan(), 0.0F, x.MYSTERIOUS_MAN_LAYER_1));
		RenderingRegistry.registerEntityRenderingHandler(EntityMysteriousManLayer2.class, new RenderDivineMob(new MysteriousMan(), 0.0F, x.MYSTERIOUS_MAN_LAYER_2));
		RenderingRegistry.registerEntityRenderingHandler(EntityMysteriousManLayer3.class, new RenderDivineMob(new MysteriousMan(), 0.0F, x.MYSTERIOUS_MAN_LAYER_3));
		RenderingRegistry.registerEntityRenderingHandler(EntityCryptKeeper.class, new RenderDivineMob(new CryptKeeper(), 0.0F, x.CRYPT_KEEPER));
		RenderingRegistry.registerEntityRenderingHandler(EntityDuo.class, new RenderDivineMob(new Duo(), 0.0F, x.DUO));
		RenderingRegistry.registerEntityRenderingHandler(EntityEhu.class, new RenderDivineMob(new Ehu(), 0.0F, x.EHU));
		RenderingRegistry.registerEntityRenderingHandler(EntityHusk.class, new RenderDivineMob(new Husk(), 0.0F, x.HUSK));
		RenderingRegistry.registerEntityRenderingHandler(EntityStoneGolem.class, new RenderDivineMob(new StoneGolem(), 0.0F, x.STONE_GOLEM));
		RenderingRegistry.registerEntityRenderingHandler(EntityGalroid.class, new RenderDivineMob(new Galroid(), 0.0F, x.GALROID));
		RenderingRegistry.registerEntityRenderingHandler(EntityHerbomancer.class, new RenderDivineMob(new Herbomancer(), 0.0F, x.HERBOMANCER));
		RenderingRegistry.registerEntityRenderingHandler(EntityKaros.class, new RenderDivineMob(new Karos(), 0.0F, x.KAROS));
		RenderingRegistry.registerEntityRenderingHandler(EntityLheiva.class, new RenderDivineMob(new Lheiva(), 0.0F, x.LHEIVA));
		RenderingRegistry.registerEntityRenderingHandler(EntityLorga.class, new RenderDivineMob(new Lorga(), 0.0F, x.LORGA));
		RenderingRegistry.registerEntityRenderingHandler(EntityLorgaFlight.class, new RenderDivineMob(new Lorgaflight(), 0.0F, x.LORGA_FLIGHT));
		RenderingRegistry.registerEntityRenderingHandler(EntityMandragora.class, new RenderDivineMob(new Mandragora(), 0.0F, x.MANDRAGORA));
		RenderingRegistry.registerEntityRenderingHandler(EntityRaglok.class, new RenderDivineMob(new RaglokGogdure(), 0.0F, x.RAGLOK));
		RenderingRegistry.registerEntityRenderingHandler(EntityTocaxin.class, new RenderDivineMob(new Tocaxin(), 0.0F, x.TOCAXIN));
		RenderingRegistry.registerEntityRenderingHandler(EntityHungerHungry.class, new RenderDivineMob(new ModelHungerHungry(), 0.0F, x.HUNGER_HUNGRY));
	}
}