package net.divinerpg.helper.blocks;

import net.divinerpg.api.blocks.BlockMod;
import net.divinerpg.api.blocks.BlockModDoor;
import net.divinerpg.api.blocks.BlockModGlass;
import net.divinerpg.api.blocks.BlockModGrass;
import net.divinerpg.api.blocks.BlockModLeaves;
import net.divinerpg.api.blocks.BlockModLog;
import net.divinerpg.api.blocks.BlockModSpawner;
import net.divinerpg.api.blocks.BlockModVine;
import net.divinerpg.api.blocks.portal.BlockModPortal;
import net.divinerpg.blocks.vethea.BlockAcid;
import net.divinerpg.blocks.vethea.BlockHelioticBeam;
import net.divinerpg.blocks.vethea.BlockInfusionTable;
import net.divinerpg.blocks.vethea.BlockKarosCannon;
import net.divinerpg.blocks.vethea.BlockKarosHeatTile;
import net.divinerpg.blocks.vethea.BlockVetheaPlant;
import net.divinerpg.helper.config.ConfigurationHelper;
import net.divinerpg.helper.items.VetheanItems;
import net.divinerpg.helper.material.EnumBlockType;
import net.divinerpg.helper.tabs.DivineRPGTabs;
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;

public class VetheaBlocks {

    public static final Block dreamwreckerSpawner    = new BlockModSpawner("dreamWreckerSpawner", "Dreamwrecker", "fireCrystal");
    public static final Block vermenousSpawner       = new BlockModSpawner("vermenousSpawner", "Vermenous", "fireCrystal");
    public static final Block twinsSpawner           = new BlockModSpawner("twinsSpawner", "Twins", "fireCrystal");
    public static final Block biphronSpawner         = new BlockModSpawner("biphronSpawner", "Biphron", "fireCrystal");
    public static final Block gorgosionSpawner       = new BlockModSpawner("gorgosionSpawner", "Gorgosion", "fireCrystal");

    public static final Block wreckAltar             = new BlockMod("wreckAltar", DivineRPGTabs.spawner);
    public static final Block quadroticAltar         = new BlockMod("quadroticAltar", DivineRPGTabs.spawner);
    public static final Block karosAltar             = new BlockMod("karosAltar", DivineRPGTabs.spawner);
    public static final Block raglokAltar            = new BlockMod("raglokAltar", DivineRPGTabs.spawner);
    public static final Block lunicAltar             = new BlockMod("lunicAltar", DivineRPGTabs.spawner);

    public static final Block vetheaPortal           = new BlockModPortal("vetheaPortal", ConfigurationHelper.vethea, TwilightBlocks.blueFire, TwilightBlocks.mortumBlock);
    public static final Block dreamStone             = new BlockMod("dreamStone", DivineRPGTabs.vethea);
    public static final Block dreamDirt              = new BlockMod(EnumBlockType.DIRT, "dreamDirt", DivineRPGTabs.vethea);
    public static final Block dreamGrass             = new BlockModGrass((BlockMod) dreamDirt, "dreamGrass");
    public static final Block fireCrystal            = new BlockMod(EnumBlockType.GLASS, "fireCrystal", DivineRPGTabs.vethea).setLightLevel(0.7F);

    public static final Block dreamWoodLog           = new BlockModLog("dreamWoodLog").setCreativeTab(DivineRPGTabs.vethea);
    public static final Block dreamWoodLeaves        = new BlockModLeaves("dreamWoodLeaves").setCreativeTab(DivineRPGTabs.vethea);
    public static final Block dreamBricks1           = new BlockMod("dreamBricks1", DivineRPGTabs.vethea);
    public static final Block dreamBricks2           = new BlockMod("dreamBricks2", DivineRPGTabs.vethea);
    public static final Block lunaStone              = new BlockMod("lunaStone", false, DivineRPGTabs.vethea);
    public static final Block lunaBricks             = new BlockMod("lunaBrick", false, DivineRPGTabs.vethea);
    public static final Block metalCaging            = new BlockMod("metalCaging", DivineRPGTabs.vethea);
    public static final Block dreamLampOn            = new BlockMod(EnumBlockType.GLASS, "dreamLampOn", false, DivineRPGTabs.vethea).setLightLevel(1);
    public static final Block dreamLamp              = new BlockMod(EnumBlockType.GLASS, "dreamLampOff", false, DivineRPGTabs.vethea);
    public static final Block weedwoodVine           = new BlockModVine("weedWoodVine").setCreativeTab(DivineRPGTabs.vethea);
    public static final Block blossomingWeedwoodVine = new BlockModVine("blossemedWeedWoodVine").setCreativeTab(DivineRPGTabs.vethea);
    public static final Block cryptWall              = new BlockMod("cryptWall", false, DivineRPGTabs.vethea);
    public static final Block smoothGlass            = new BlockModGlass("smoothGlass").setCreativeTab(DivineRPGTabs.vethea);
    public static final Block villageLamp            = new BlockMod(EnumBlockType.GLASS, "villageLamp", DivineRPGTabs.vethea).setLightLevel(1);
    public static final Block cellLamp               = new BlockMod(EnumBlockType.GLASS, "cellLamp", DivineRPGTabs.vethea).setLightLevel(1);
    public static final Block barredDoor             = new BlockModDoor(EnumBlockType.IRON, "barredDoorBlock", VetheanItems.barredDoorItem, null);
    public static final Block firelight              = new BlockMod(EnumBlockType.GLASS, "firelight", DivineRPGTabs.vethea).setLightLevel(1).setResistance(1);
    public static final Block hyrewood               = new BlockModLog("hyreWoodLog").setCreativeTab(DivineRPGTabs.vethea);
    public static final Block mintwoodLeaves         = new BlockModLeaves("mintwoodLeaves").setCreativeTab(DivineRPGTabs.vethea);
    public static final Block firewall               = new BlockMod("fireWall", DivineRPGTabs.vethea);
    public static final Block karosHeatTileGreen     = new BlockKarosHeatTile(false, "karosHeatTileGreen");
    public static final Block karosHeatTileRed       = new BlockKarosHeatTile(true, "karosHeatTileRed");
    public static final Block firewood               = new BlockModLog("fireWoodLog").setCreativeTab(DivineRPGTabs.vethea);
    public static final Block bacterialAcid          = new BlockAcid("bacterialAcid");
    public static final Block blockAcid              = new BlockAcid("acidBlock");
    public static final Block everstone              = new BlockMod("greenEverstone", false, DivineRPGTabs.vethea);
    public static final Block lunicAcid              = new BlockAcid("lunicAcid");
    public static final Block firewoodLeaves         = new BlockModLeaves("fireWoodLeaves").setCreativeTab(DivineRPGTabs.vethea);
    public static final Block hyrewoodLeaves         = new BlockModLeaves("hyreWoodLeaves").setCreativeTab(DivineRPGTabs.vethea);
    public static final Block gemtopGreen            = new BlockVetheaPlant().setName("greenGemTop");
    public static final Block purpleDulah            = new BlockVetheaPlant().setName("purpleDulah");
    public static final Block yellowDulah            = new BlockVetheaPlant().setName("yellowDulah");
    public static final Block greenDulah             = new BlockVetheaPlant().setName("greenDulah");
    public static final Block mintwood               = new BlockModLog("mintWoodLog").setCreativeTab(DivineRPGTabs.vethea);
    public static final Block cracklespike           = new BlockVetheaPlant().setName("crackleSpike");
    public static final Block fernite                = new BlockVetheaPlant().setName("fernite");
    public static final Block bulatobe               = new BlockVetheaPlant().setName("bulbatobe");
    public static final Block shineGrass             = new BlockVetheaPlant().setName("shineGrass").setLightLevel(0.4F);
    //public static final Block             shimmer                = new BlockShimmer().setLightLevel(0.4F).setUnlocalizedName("shimmer").setStepSound(Block.soundGrassFootstep);
    public static final Block hiveWall               = new BlockMod(EnumBlockType.GLASS, "hiveWalls", DivineRPGTabs.vethea).setLightLevel(0.533F);
    //public static final Block             dreamglow              = new BlockShimmer().setLightLevel(0.4F).setUnlocalizedName("dreamglow").setStepSound(Block.soundGrassFootstep);
    public static final Block hyrewoodVine           = new BlockModVine("hyreWoodVine").setCreativeTab(DivineRPGTabs.vethea);
    public static final Block chamberWall            = new BlockMod("chamberWall1", false, DivineRPGTabs.vethea);
    public static final Block chamberWall1           = new BlockMod("chamberWall2", false, DivineRPGTabs.vethea);
    public static final Block chamberWall2           = new BlockMod("chamberWall3", false, DivineRPGTabs.vethea);
    public static final Block whiteEverstone         = new BlockMod("whiteEverstone", false, DivineRPGTabs.vethea);
    public static final Block darkEverstone          = new BlockMod("darkEverstone", false, DivineRPGTabs.vethea);
    public static final Block hungerstone1           = new BlockMod("hungerStone1", DivineRPGTabs.vethea);
    public static final Block hungerstone2           = new BlockMod("hungerStone2", DivineRPGTabs.vethea);
    public static final Block cryptFloor             = new BlockMod("cryptFloor", false, DivineRPGTabs.vethea);
    public static final Block hallWall               = new BlockMod("hallWall", false, DivineRPGTabs.vethea);
    public static final Block karosBricks            = new BlockMod("karosBrick", false, DivineRPGTabs.vethea);
    public static final Block karosBricks2           = new BlockMod("KarosBrick2", false, DivineRPGTabs.vethea);
    public static final Block infusionTable          = new BlockInfusionTable().setName("infusionTable").setBlockUnbreakable();
    public static final Block helioticBeam           = new BlockHelioticBeam("helioticBeam");
    public static final Block karosCannon            = new BlockKarosCannon(Material.rock).setName("karosCannon");
}
