package net.divinerpg.helper.entity;

import net.divinerpg.entity.vethea.EntityAcidHag;
import net.divinerpg.entity.vethea.EntityBiphron;
import net.divinerpg.entity.vethea.EntityBohemite;
import net.divinerpg.entity.vethea.EntityCryptKeeper;
import net.divinerpg.entity.vethea.EntityCymesoid;
import net.divinerpg.entity.vethea.EntityDissiment;
import net.divinerpg.entity.vethea.EntityDreamwrecker;
import net.divinerpg.entity.vethea.EntityDuo;
import net.divinerpg.entity.vethea.EntityEhu;
import net.divinerpg.entity.vethea.EntityEndiku;
import net.divinerpg.entity.vethea.EntityEnt;
import net.divinerpg.entity.vethea.EntityGalroid;
import net.divinerpg.entity.vethea.EntityGorgosion;
import net.divinerpg.entity.vethea.EntityHelio;
import net.divinerpg.entity.vethea.EntityHiveQueen;
import net.divinerpg.entity.vethea.EntityHiveSoldier;
import net.divinerpg.entity.vethea.EntityHoverStinger;
import net.divinerpg.entity.vethea.EntityHungerHungry;
import net.divinerpg.entity.vethea.EntityHusk;
import net.divinerpg.entity.vethea.EntityKaros;
import net.divinerpg.entity.vethea.EntityKazrotic;
import net.divinerpg.entity.vethea.EntityLadyLuna;
import net.divinerpg.entity.vethea.EntityLheiva;
import net.divinerpg.entity.vethea.EntityLorga;
import net.divinerpg.entity.vethea.EntityLorgaFlight;
import net.divinerpg.entity.vethea.EntityMandragora;
import net.divinerpg.entity.vethea.EntityMysteriousManLayer1;
import net.divinerpg.entity.vethea.EntityMysteriousManLayer2;
import net.divinerpg.entity.vethea.EntityMysteriousManLayer3;
import net.divinerpg.entity.vethea.EntityQuadro;
import net.divinerpg.entity.vethea.EntityRaglok;
import net.divinerpg.entity.vethea.EntityShadahier;
import net.divinerpg.entity.vethea.EntityStoneGolem;
import net.divinerpg.entity.vethea.EntityTempleGuardian;
import net.divinerpg.entity.vethea.EntityTocaxin;
import net.divinerpg.entity.vethea.EntityTwins;
import net.divinerpg.entity.vethea.EntityVermenous;
import net.divinerpg.entity.vethea.EntityVhraak;
import net.divinerpg.entity.vethea.EntityWreck;
import net.divinerpg.entity.vethea.EntityZone;
import net.divinerpg.entity.vethea.EntityZoragon;
import net.divinerpg.entity.vethea.projectile.EntityAmthirmisDisk;
import net.divinerpg.entity.vethea.projectile.EntityArksianeDisk;
import net.divinerpg.entity.vethea.projectile.EntityBouncingProjectile;
import net.divinerpg.entity.vethea.projectile.EntityCermileDisk;
import net.divinerpg.entity.vethea.projectile.EntityDarvenDisk;
import net.divinerpg.entity.vethea.projectile.EntityEvernightProjectile;
import net.divinerpg.entity.vethea.projectile.EntityEversightProjectile;
import net.divinerpg.entity.vethea.projectile.EntityHeliosisDisk;
import net.divinerpg.entity.vethea.projectile.EntityKarosDisk;
import net.divinerpg.entity.vethea.projectile.EntityPardimalDisk;
import net.divinerpg.entity.vethea.projectile.EntityQuadroticDisk;
import net.divinerpg.entity.vethea.projectile.EntityTeakerDisk;
import net.divinerpg.entity.vethea.projectile.EntityVetheanCannonEversight;
import net.divinerpg.entity.vethea.projectile.EntityVetheanCannonShot;
import net.divinerpg.helper.DivineAPI;

public class VetheaEntityRegistry {

	public static void init(){
		DivineAPI.registerProjectile(EntityAmthirmisDisk.class, "Amthirmis Disk");
		DivineAPI.registerProjectile(EntityArksianeDisk.class, "Arksiane Disk");
		DivineAPI.registerProjectile(EntityCermileDisk.class, "Cermile Disk");
		DivineAPI.registerProjectile(EntityDarvenDisk.class, "Darven Disk");
		DivineAPI.registerProjectile(EntityHeliosisDisk.class, "Heliosis Disk");
		DivineAPI.registerProjectile(EntityKarosDisk.class, "Karos Disk");
		DivineAPI.registerProjectile(EntityPardimalDisk.class, "Pardimal Disk");
		DivineAPI.registerProjectile(EntityQuadroticDisk.class, "Quadrotic Disk");
		DivineAPI.registerProjectile(EntityTeakerDisk.class, "Teaker Disk");
		
		DivineAPI.registerProjectile(EntityBouncingProjectile.class, "Staff");
		DivineAPI.registerProjectile(EntityEvernightProjectile.class, "Evernight");
		DivineAPI.registerProjectile(EntityVetheanCannonShot.class, "Cannon");
		DivineAPI.registerProjectile(EntityVetheanCannonEversight.class, "Cannon Eversight");
		DivineAPI.registerProjectile(EntityEversightProjectile.class, "Eversight");
		
		DivineAPI.registerDivineRPGMob(EntityVermenous.class, "Vermenous", DivineAPI.mobID++);
        DivineAPI.registerDivineRPGMob(EntityEnt.class, "Ent", DivineAPI.mobID++);
        DivineAPI.registerDivineRPGMob(EntityCymesoid.class, "Cymesoid", DivineAPI.mobID++);
        DivineAPI.registerDivineRPGMob(EntityDreamwrecker.class, "Dream Wrecker", DivineAPI.mobID++);
        DivineAPI.registerDivineRPGMob(EntityTocaxin.class, "Tocaxin", DivineAPI.mobID++);
        DivineAPI.registerDivineRPGMob(EntityShadahier.class, "Shadahier", DivineAPI.mobID++);
        DivineAPI.registerDivineRPGMob(EntityAcidHag.class, "Acid Hag", DivineAPI.mobID++);
        DivineAPI.registerDivineRPGMob(EntityKazrotic.class, "Kazrotic", DivineAPI.mobID++);
        DivineAPI.registerDivineRPGMob(EntityHelio.class, "Helio", DivineAPI.mobID++);
        DivineAPI.registerDivineRPGMob(EntityGorgosion.class, "Gorgosion", DivineAPI.mobID++);
        DivineAPI.registerDivineRPGMob(EntityHoverStinger.class, "Hoverstinger", DivineAPI.mobID++);
        DivineAPI.registerDivineRPGMob(EntityZone.class, "Zone", DivineAPI.mobID++);
        DivineAPI.registerDivineRPGMob(EntityZoragon.class, "Zoragon", DivineAPI.mobID++);
        DivineAPI.registerDivineRPGMob(EntityDissiment.class, "Dissiment", DivineAPI.mobID++);
        DivineAPI.registerDivineRPGMob(EntityVhraak.class, "Vhraak", DivineAPI.mobID++);
        DivineAPI.registerDivineRPGMob(EntityGalroid.class, "Galroid", DivineAPI.mobID++);
        DivineAPI.registerDivineRPGMob(EntityLadyLuna.class, "Lady Luna", DivineAPI.mobID++);
        DivineAPI.registerDivineRPGMob(EntityBohemite.class, "Bohemite", DivineAPI.mobID++);
        DivineAPI.registerDivineRPGMob(EntityWreck.class, "Wreck", DivineAPI.mobID++);
        DivineAPI.registerDivineRPGMob(EntityBiphron.class, "Biphron", DivineAPI.mobID++);
        DivineAPI.registerDivineRPGMob(EntityHiveQueen.class, "Hive Queen", DivineAPI.mobID++);
        DivineAPI.registerDivineRPGMob(EntityHiveSoldier.class, "hivesoldier", DivineAPI.mobID++);
        DivineAPI.registerDivineRPGMob(EntityLheiva.class, "lheiva", DivineAPI.mobID++);
        DivineAPI.registerDivineRPGMob(EntityMandragora.class, "mandragora", DivineAPI.mobID++);
        DivineAPI.registerDivineRPGMob(EntityTwins.class, "Twins", DivineAPI.mobID++);
        DivineAPI.registerDivineRPGMob(EntityKaros.class, "Karos", DivineAPI.mobID++);
        DivineAPI.registerDivineRPGMob(EntityRaglok.class, "Raglok", DivineAPI.mobID++);
        DivineAPI.registerDivineRPGMob(EntityQuadro.class, "Quadro", DivineAPI.mobID++);
        DivineAPI.registerDivineRPGMob(EntityDuo.class, "Duo", DivineAPI.mobID++);
        DivineAPI.registerDivineRPGMob(EntityEndiku.class, "Endiku", DivineAPI.mobID++);
        DivineAPI.registerDivineRPGMob(EntityLorga.class, "Lorga", DivineAPI.mobID++);
        DivineAPI.registerDivineRPGMob(EntityLorgaFlight.class, "Lorga Flight", DivineAPI.mobID++);
        DivineAPI.registerDivineRPGMob(EntityMysteriousManLayer1.class, "Mysterious Man 1", DivineAPI.mobID++);
        DivineAPI.registerDivineRPGMob(EntityMysteriousManLayer2.class, "Mysterious Man 2", DivineAPI.mobID++);
        DivineAPI.registerDivineRPGMob(EntityMysteriousManLayer3.class, "Mysterious Man 3", DivineAPI.mobID++);
        DivineAPI.registerDivineRPGMob(EntityHungerHungry.class, "Hunger Hungry", DivineAPI.mobID++);
        DivineAPI.registerDivineRPGMob(EntityCryptKeeper.class, "Crypt Keeper", DivineAPI.mobID++);
        DivineAPI.registerDivineRPGMob(EntityTempleGuardian.class, "Temple Guardian", DivineAPI.mobID++);
        DivineAPI.registerDivineRPGMob(EntityEhu.class, "Ehu", DivineAPI.mobID++);
        DivineAPI.registerDivineRPGMob(EntityStoneGolem.class, "Stone Golem", DivineAPI.mobID++);
        DivineAPI.registerDivineRPGMob(EntityHusk.class, "Husk", DivineAPI.mobID++);
	}
}