package divinerpg.helper.mobs;

import divinerpg.helper.DivineAPI;
import divinerpg.twilight.entity.mob.EntityAngryBunny;
import divinerpg.twilight.entity.mob.EntityApalachiaArcher;
import divinerpg.twilight.entity.mob.EntityApalachiaCadillion;
import divinerpg.twilight.entity.mob.EntityApalachiaGolem;
import divinerpg.twilight.entity.mob.EntityApalachiaTomo;
import divinerpg.twilight.entity.mob.EntityApalachiaWarrior;
import divinerpg.twilight.entity.mob.EntityBaslisk;
import divinerpg.twilight.entity.mob.EntityBunny;
import divinerpg.twilight.entity.mob.EntityCadillion;
import divinerpg.twilight.entity.mob.EntityCori;
import divinerpg.twilight.entity.mob.EntityCori2;
import divinerpg.twilight.entity.mob.EntityDensos;
import divinerpg.twilight.entity.mob.EntityEdenTomo;
import divinerpg.twilight.entity.mob.EntityKarot;
import divinerpg.twilight.entity.mob.EntityMadivel;
import divinerpg.twilight.entity.mob.EntityMoonWolf;
import divinerpg.twilight.entity.mob.EntityMortumCadillion;
import divinerpg.twilight.entity.mob.EntityMortumDemon;
import divinerpg.twilight.entity.mob.EntityNesro;
import divinerpg.twilight.entity.mob.EntityReyvor;
import divinerpg.twilight.entity.mob.EntitySamek;
import divinerpg.twilight.entity.mob.EntitySkythernArcher;
import divinerpg.twilight.entity.mob.EntitySkythernFiend;
import divinerpg.twilight.entity.mob.EntitySkythernGolem;
import divinerpg.twilight.entity.mob.EntitySoulFiend;
import divinerpg.twilight.entity.mob.EntitySoulStealer;
import divinerpg.twilight.entity.mob.EntityTwilightDemon;
import divinerpg.twilight.entity.mob.EntityVamacheron;
import divinerpg.twilight.entity.mob.EntityVerek;
import divinerpg.twilight.entity.mob.EntityWildWoodGolem;
import divinerpg.twilight.entity.mob.EntityWildWoodTomo;
import divinerpg.twilight.entity.projectile.EntityApalachiaArrow;
import divinerpg.twilight.entity.projectile.EntityEdenArrow;
import divinerpg.twilight.entity.projectile.EntityHaliteArrow;
import divinerpg.twilight.entity.projectile.EntityMortumArrow;
import divinerpg.twilight.entity.projectile.EntityPhaserApalachia;
import divinerpg.twilight.entity.projectile.EntityPhaserEden;
import divinerpg.twilight.entity.projectile.EntityPhaserHalite;
import divinerpg.twilight.entity.projectile.EntityPhaserMortum;
import divinerpg.twilight.entity.projectile.EntityPhaserSkythern;
import divinerpg.twilight.entity.projectile.EntityPhaserWildWood;
import divinerpg.twilight.entity.projectile.EntitySkythernArrow;
import divinerpg.twilight.entity.projectile.EntitySlicerApalachia;
import divinerpg.twilight.entity.projectile.EntitySlicerEden;
import divinerpg.twilight.entity.projectile.EntitySlicerHalite;
import divinerpg.twilight.entity.projectile.EntitySlicerMortum;
import divinerpg.twilight.entity.projectile.EntitySlicerSkythern;
import divinerpg.twilight.entity.projectile.EntitySlicerWildWoods;
import divinerpg.twilight.entity.projectile.EntityWildArrow;

public class TwilightMobRegistry {

	public static void init(){
	    DivineAPI.registerProjectile(EntitySlicerEden.class, "edenSlicer");
	    DivineAPI.registerProjectile(EntitySlicerWildWoods.class, "wildSlicer");
        DivineAPI.registerProjectile(EntitySlicerApalachia.class, "apalachiaSlicer");
        DivineAPI.registerProjectile(EntitySlicerSkythern.class, "skythernSlicer");
        DivineAPI.registerProjectile(EntitySlicerMortum.class, "mortumSlicer");
        DivineAPI.registerProjectile(EntitySlicerHalite.class, "haliteSlicer");
        DivineAPI.registerProjectile(EntityPhaserEden.class, "edenPhaser");
        DivineAPI.registerProjectile(EntityPhaserWildWood.class, "wildPhaser");
        DivineAPI.registerProjectile(EntityPhaserApalachia.class, "apalachiaPhaser");
        DivineAPI.registerProjectile(EntityPhaserSkythern.class, "skythernPhaser");
        DivineAPI.registerProjectile(EntityPhaserMortum.class, "mortumPhaser");
        DivineAPI.registerProjectile(EntityPhaserHalite.class, "halitePhaser");
        
        DivineAPI.registerDivineRPGMob(EntityCadillion.class, "Cadillion");
        DivineAPI.registerDivineRPGMob(EntityEdenTomo.class, "Eden Tomo");
        DivineAPI.registerDivineRPGMob(EntityBunny.class, "Bunny");
        DivineAPI.registerDivineRPGMob(EntityAngryBunny.class, "Angry Bunny");
        DivineAPI.registerDivineRPGMob(EntityCori.class, "Eden Cori");
        DivineAPI.registerDivineRPGMob(EntityMadivel.class, "Madivel");
        DivineAPI.registerDivineRPGMob(EntityNesro.class, "Nesro");
        DivineAPI.registerDivineRPGMob(EntityWildWoodGolem.class, "WildWood Golem");
        DivineAPI.registerDivineRPGMob(EntityWildWoodTomo.class, "WildWood Tomo");
        DivineAPI.registerDivineRPGMob(EntityVerek.class, "Verek");
        DivineAPI.registerDivineRPGMob(EntityMoonWolf.class, "Moon Wolf");
        DivineAPI.registerDivineRPGMob(EntityApalachiaCadillion.class, "Apalachia Cadillion");
        DivineAPI.registerDivineRPGMob(EntityApalachiaTomo.class, "Apalachia Tomo");
        DivineAPI.registerDivineRPGMob(EntityApalachiaGolem.class, "Apalachia Golem");
        DivineAPI.registerDivineRPGMob(EntityApalachiaWarrior.class, "Enchant Warrior");
        DivineAPI.registerDivineRPGMob(EntitySkythernArcher.class, "Skythern Archer");
        DivineAPI.registerDivineRPGMob(EntityApalachiaArcher.class, "Twilight Archer");
        DivineAPI.registerDivineRPGMob(EntitySamek.class, "Samek");
        DivineAPI.registerDivineRPGMob(EntitySkythernGolem.class, "Skythern Golem");
        DivineAPI.registerDivineRPGMob(EntityCori2.class, "Skythern Cori");
        DivineAPI.registerDivineRPGMob(EntitySkythernFiend.class, "Skythern Fiend");
        DivineAPI.registerDivineRPGMob(EntityMortumCadillion.class, "Mortum Cadillion");
        DivineAPI.registerDivineRPGMob(EntityMortumDemon.class, "Mortum Demon");
        DivineAPI.registerDivineRPGMob(EntityBaslisk.class, "Baslisk");
        DivineAPI.registerDivineRPGMob(EntitySoulStealer.class, "Soul Stealer");
        DivineAPI.registerDivineRPGMob(EntityDensos.class, "Densos");
        DivineAPI.registerDivineRPGMob(EntityReyvor.class, "Reyvor");
        DivineAPI.registerDivineRPGMob(EntityTwilightDemon.class, "Twilight Demon");
        DivineAPI.registerDivineRPGMob(EntitySoulFiend.class, "Soul Fiend");
        DivineAPI.registerDivineRPGMob(EntityVamacheron.class, "Vamacheron");
        DivineAPI.registerDivineRPGMob(EntityKarot.class, "Karot");
        
        DivineAPI.registerProjectile(EntityEdenArrow.class, "Eden Arrow");
        DivineAPI.registerProjectile(EntityWildArrow.class, "Wild Arrow");
        DivineAPI.registerProjectile(EntityApalachiaArrow.class, "Apalachia Arrow");
        DivineAPI.registerProjectile(EntitySkythernArrow.class, "Skythern Arrow");
        DivineAPI.registerProjectile(EntityMortumArrow.class, "Mortum Arrow");
        DivineAPI.registerProjectile(EntityHaliteArrow.class, "Halite Arrow");
	}
}